// protoc-gen-gores - Protobuf代码生成器插件
// 生成资源管理器的Go访问接口代码

package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Messages) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_res.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-gores. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// 生成导入
	g.P("import (")
	g.P(`	"encoding/binary"`)
	g.P(`	"fmt"`)
	g.P(`	"io"`)
	g.P(`	"os"`)
	g.P(`	"sync"`)
	g.P()
	g.P(`	"google.golang.org/protobuf/proto"`)
	g.P(")")
	g.P()

	// 为每个消息生成资源管理器
	for _, msg := range file.Messages {
		generateResourceManager(g, msg)
	}
}

func generateResourceManager(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgName := msg.GoIdent.GoName

	// 分析字段,找出主键和索引
	var primaryKeyField *protogen.Field
	var indexFields []*protogen.Field
	var uniqueIndexFields []*protogen.Field

	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		if opts.IsPrimaryKey {
			primaryKeyField = field
		}
		if opts.IndexType == IndexTypeUnique {
			uniqueIndexFields = append(uniqueIndexFields, field)
		} else if opts.IndexType == IndexTypeNormal {
			indexFields = append(indexFields, field)
		}
	}

	// 生成资源管理器结构体
	g.P("// ", msgName, "Manager 管理", msgName, "资源的加载和访问")
	g.P("type ", msgName, "Manager struct {")
	g.P("	mu sync.RWMutex")
	g.P("	items []*", msgName)
	if primaryKeyField != nil {
		keyType := getGoTypeName(primaryKeyField)
		g.P("	byPrimaryKey map[", keyType, "]*", msgName)
	}
	for _, field := range uniqueIndexFields {
		keyType := getGoTypeName(field)
		g.P("	by", field.GoName, " map[", keyType, "]*", msgName)
	}
	for _, field := range indexFields {
		keyType := getGoTypeName(field)
		g.P("	by", field.GoName, " map[", keyType, "][]*", msgName)
	}
	g.P("}")
	g.P()

	// 生成全局实例
	g.P("var (")
	g.P("	_", msgName, "Manager     *", msgName, "Manager")
	g.P("	_", msgName, "ManagerOnce sync.Once")
	g.P(")")
	g.P()

	// 生成获取管理器实例的函数
	g.P("// Get", msgName, "Manager 获取", msgName, "资源管理器单例")
	g.P("func Get", msgName, "Manager() *", msgName, "Manager {")
	g.P("	_", msgName, "ManagerOnce.Do(func() {")
	g.P("		_", msgName, "Manager = &", msgName, "Manager{}")
	g.P("	})")
	g.P("	return _", msgName, "Manager")
	g.P("}")
	g.P()

	// 生成加载函数
	g.P("// Load 从二进制文件加载资源")
	g.P("func (m *", msgName, "Manager) Load(path string) error {")
	g.P("	data, err := os.ReadFile(path)")
	g.P("	if err != nil {")
	g.P("		return fmt.Errorf(\"failed to read file: %w\", err)")
	g.P("	}")
	g.P("	return m.LoadFromBytes(data)")
	g.P("}")
	g.P()

	// 生成从字节加载函数
	g.P("// LoadFromBytes 从字节数据加载资源")
	g.P("func (m *", msgName, "Manager) LoadFromBytes(data []byte) error {")
	g.P("	if len(data) < 4 {")
	g.P("		return fmt.Errorf(\"invalid data: too short\")")
	g.P("	}")
	g.P()
	g.P("	count := binary.LittleEndian.Uint32(data[:4])")
	g.P("	offset := 4")
	g.P()
	g.P("	items := make([]*", msgName, ", 0, count)")
	if primaryKeyField != nil {
		keyType := getGoTypeName(primaryKeyField)
		g.P("	byPrimaryKey := make(map[", keyType, "]*", msgName, ", count)")
	}
	for _, field := range uniqueIndexFields {
		keyType := getGoTypeName(field)
		g.P("	by", field.GoName, " := make(map[", keyType, "]*", msgName, ", count)")
	}
	for _, field := range indexFields {
		keyType := getGoTypeName(field)
		g.P("	by", field.GoName, " := make(map[", keyType, "][]*", msgName, ")")
	}
	g.P()
	g.P("	for i := uint32(0); i < count; i++ {")
	g.P("		if offset+4 > len(data) {")
	g.P("			return io.ErrUnexpectedEOF")
	g.P("		}")
	g.P("		length := binary.LittleEndian.Uint32(data[offset : offset+4])")
	g.P("		offset += 4")
	g.P()
	g.P("		if offset+int(length) > len(data) {")
	g.P("			return io.ErrUnexpectedEOF")
	g.P("		}")
	g.P()
	g.P("		item := &", msgName, "{}")
	g.P("		if err := proto.Unmarshal(data[offset:offset+int(length)], item); err != nil {")
	g.P("			return fmt.Errorf(\"failed to unmarshal item %d: %w\", i, err)")
	g.P("		}")
	g.P("		offset += int(length)")
	g.P()
	g.P("		items = append(items, item)")
	if primaryKeyField != nil {
		g.P("		byPrimaryKey[item.", primaryKeyField.GoName, "] = item")
	}
	for _, field := range uniqueIndexFields {
		g.P("		by", field.GoName, "[item.", field.GoName, "] = item")
	}
	for _, field := range indexFields {
		g.P("		by", field.GoName, "[item.", field.GoName, "] = append(by", field.GoName, "[item.", field.GoName, "], item)")
	}
	g.P("	}")
	g.P()
	g.P("	m.mu.Lock()")
	g.P("	m.items = items")
	if primaryKeyField != nil {
		g.P("	m.byPrimaryKey = byPrimaryKey")
	}
	for _, field := range uniqueIndexFields {
		g.P("	m.by", field.GoName, " = by", field.GoName)
	}
	for _, field := range indexFields {
		g.P("	m.by", field.GoName, " = by", field.GoName)
	}
	g.P("	m.mu.Unlock()")
	g.P()
	g.P("	return nil")
	g.P("}")
	g.P()

	// 生成获取所有项目的函数
	g.P("// GetAll 获取所有", msgName, "资源")
	g.P("func (m *", msgName, "Manager) GetAll() []*", msgName, " {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	result := make([]*", msgName, ", len(m.items))")
	g.P("	copy(result, m.items)")
	g.P("	return result")
	g.P("}")
	g.P()

	// 生成获取数量的函数
	g.P("// Count 获取资源数量")
	g.P("func (m *", msgName, "Manager) Count() int {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	return len(m.items)")
	g.P("}")
	g.P()

	// 生成主键访问函数
	if primaryKeyField != nil {
		keyType := getGoTypeName(primaryKeyField)
		g.P("// Get 根据主键获取", msgName)
		g.P("func (m *", msgName, "Manager) Get(key ", keyType, ") (*", msgName, ", bool) {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	item, ok := m.byPrimaryKey[key]")
		g.P("	return item, ok")
		g.P("}")
		g.P()

		g.P("// MustGet 根据主键获取", msgName, ",不存在时panic")
		g.P("func (m *", msgName, "Manager) MustGet(key ", keyType, ") *", msgName, " {")
		g.P("	item, ok := m.Get(key)")
		g.P("	if !ok {")
		g.P("		panic(fmt.Sprintf(\"", msgName, " with key %v not found\", key))")
		g.P("	}")
		g.P("	return item")
		g.P("}")
		g.P()

		g.P("// Has 检查主键是否存在")
		g.P("func (m *", msgName, "Manager) Has(key ", keyType, ") bool {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	_, ok := m.byPrimaryKey[key]")
		g.P("	return ok")
		g.P("}")
		g.P()
	}

	// 生成唯一索引访问函数
	for _, field := range uniqueIndexFields {
		keyType := getGoTypeName(field)
		g.P("// GetBy", field.GoName, " 根据", field.GoName, "获取", msgName)
		g.P("func (m *", msgName, "Manager) GetBy", field.GoName, "(key ", keyType, ") (*", msgName, ", bool) {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	item, ok := m.by", field.GoName, "[key]")
		g.P("	return item, ok")
		g.P("}")
		g.P()
	}

	// 生成普通索引访问函数
	for _, field := range indexFields {
		keyType := getGoTypeName(field)
		g.P("// GetBy", field.GoName, " 根据", field.GoName, "获取", msgName, "列表")
		g.P("func (m *", msgName, "Manager) GetBy", field.GoName, "(key ", keyType, ") []*", msgName, " {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	items := m.by", field.GoName, "[key]")
		g.P("	if items == nil {")
		g.P("		return nil")
		g.P("	}")
		g.P("	result := make([]*", msgName, ", len(items))")
		g.P("	copy(result, items)")
		g.P("	return result")
		g.P("}")
		g.P()
	}

	// 生成遍历函数
	g.P("// Range 遍历所有", msgName, "资源")
	g.P("func (m *", msgName, "Manager) Range(fn func(item *", msgName, ") bool) {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	for _, item := range m.items {")
	g.P("		if !fn(item) {")
	g.P("			break")
	g.P("		}")
	g.P("	}")
	g.P("}")
	g.P()

	// 生成过滤函数
	g.P("// Filter 过滤", msgName, "资源")
	g.P("func (m *", msgName, "Manager) Filter(fn func(item *", msgName, ") bool) []*", msgName, " {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	var result []*", msgName)
	g.P("	for _, item := range m.items {")
	g.P("		if fn(item) {")
	g.P("			result = append(result, item)")
	g.P("		}")
	g.P("	}")
	g.P("	return result")
	g.P("}")
	g.P()
}

// IndexType 索引类型
type IndexType int

const (
	IndexTypeNone   IndexType = 0
	IndexTypeUnique IndexType = 1
	IndexTypeNormal IndexType = 2
)

// FieldOptions 字段选项
type FieldOptions struct {
	IsPrimaryKey bool
	IndexType    IndexType
	IndexName    string
}

// getFieldOptions 获取字段选项
func getFieldOptions(field *protogen.Field) FieldOptions {
	opts := FieldOptions{}

	// 从proto选项中获取自定义属性
	// 这里通过解析描述符选项来获取
	if field.Desc.Options() != nil {
		// 检查是否有自定义选项
		// 在实际使用中,需要注册并解析自定义选项
		// 这里使用字段注释作为替代方案
		comments := string(field.Comments.Leading)
		if containsTag(comments, "@primary_key") {
			opts.IsPrimaryKey = true
		}
		if containsTag(comments, "@unique") {
			opts.IndexType = IndexTypeUnique
		}
		if containsTag(comments, "@index") {
			opts.IndexType = IndexTypeNormal
		}
	}

	return opts
}

// containsTag 检查注释中是否包含指定标签
func containsTag(comments, tag string) bool {
	return len(comments) > 0 && (comments == tag || 
		len(comments) > len(tag) && 
		(comments[:len(tag)] == tag || 
		 comments[len(comments)-len(tag):] == tag ||
		 containsSubstring(comments, " "+tag+" ") ||
		 containsSubstring(comments, " "+tag+"\n") ||
		 containsSubstring(comments, "\n"+tag+" ") ||
		 containsSubstring(comments, "\n"+tag+"\n")))
}

func containsSubstring(s, substr string) bool {
	return len(s) >= len(substr) && findSubstring(s, substr) >= 0
}

func findSubstring(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}

// getGoTypeName 获取Go类型名
func getGoTypeName(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case 1: // double
		return "float64"
	case 2: // float
		return "float32"
	case 3, 4, 18: // int64, uint64, sint64
		return "int64"
	case 5, 17: // int32, sint32
		return "int32"
	case 6, 7: // fixed64, fixed32
		return "uint64"
	case 8: // bool
		return "bool"
	case 9: // string
		return "string"
	case 12: // bytes
		return "[]byte"
	case 13: // uint32
		return "uint32"
	case 14: // enum
		return field.Enum.GoIdent.GoName
	case 15, 16: // sfixed32, sfixed64
		return "int32"
	default:
		return "interface{}"
	}
}
