// protoc-gen-gores - Protobuf代码生成器插件
// 生成资源管理器的Go访问接口代码

package main

import (
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	goresproto "github.com/example/gores/proto"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Messages) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_res.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-gores. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// 生成导入
	g.P("import (")
	g.P(`	"encoding/binary"`)
	g.P(`	"fmt"`)
	g.P(`	"io"`)
	g.P(`	"os"`)
	g.P(`	"sync"`)
	g.P()
	g.P(`	"google.golang.org/protobuf/proto"`)
	g.P(")")
	g.P()

	// 为每个消息生成资源管理器
	for _, msg := range file.Messages {
		generateResourceManager(g, msg)
	}
}

// getFieldOptions 从字段描述符中获取自定义选项
func getFieldOptions(field *protogen.Field) *goresproto.FieldOptions {
	opts := field.Desc.Options()
	if opts == nil {
		return nil
	}

	// 使用 proto.GetExtension 获取自定义字段选项
	ext := proto.GetExtension(opts, goresproto.E_Field)
	if ext == nil {
		return nil
	}

	fieldOpts, ok := ext.(*goresproto.FieldOptions)
	if !ok {
		return nil
	}

	return fieldOpts
}

// getResourceOptions 从消息描述符中获取自定义选项
func getResourceOptions(msg *protogen.Message) *goresproto.ResourceOptions {
	opts := msg.Desc.Options()
	if opts == nil {
		return nil
	}

	// 使用 proto.GetExtension 获取自定义资源选项
	ext := proto.GetExtension(opts, goresproto.E_Resource)
	if ext == nil {
		return nil
	}

	resOpts, ok := ext.(*goresproto.ResourceOptions)
	if !ok {
		return nil
	}

	return resOpts
}

// FieldMeta 字段元信息
type FieldMeta struct {
	Field        *protogen.Field
	IsPrimaryKey bool
	IndexType    goresproto.IndexType
	IndexName    string
	IndexOrder   int32
}

// analyzeFields 分析消息的所有字段,提取主键和索引信息
func analyzeFields(msg *protogen.Message) (primaryKey *FieldMeta, uniqueIndexes, normalIndexes []*FieldMeta, compositeIndexes map[string][]*FieldMeta) {
	compositeIndexes = make(map[string][]*FieldMeta)

	for _, field := range msg.Fields {
		opts := getFieldOptions(field)
		if opts == nil {
			continue
		}

		meta := &FieldMeta{
			Field:        field,
			IsPrimaryKey: opts.GetPrimaryKey(),
			IndexType:    opts.GetIndex(),
			IndexName:    opts.GetIndexName(),
			IndexOrder:   opts.GetIndexOrder(),
		}

		// 处理主键
		if meta.IsPrimaryKey {
			primaryKey = meta
		}

		// 处理索引
		switch meta.IndexType {
		case goresproto.IndexType_INDEX_UNIQUE:
			uniqueIndexes = append(uniqueIndexes, meta)
		case goresproto.IndexType_INDEX_NORMAL:
			normalIndexes = append(normalIndexes, meta)
		case goresproto.IndexType_INDEX_COMPOSITE:
			if meta.IndexName != "" {
				compositeIndexes[meta.IndexName] = append(compositeIndexes[meta.IndexName], meta)
			}
		}
	}

	// 对复合索引按顺序排序
	for name := range compositeIndexes {
		fields := compositeIndexes[name]
		// 简单冒泡排序
		for i := 0; i < len(fields)-1; i++ {
			for j := i + 1; j < len(fields); j++ {
				if fields[i].IndexOrder > fields[j].IndexOrder {
					fields[i], fields[j] = fields[j], fields[i]
				}
			}
		}
	}

	return
}

func generateResourceManager(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgName := msg.GoIdent.GoName

	// 获取资源选项
	resOpts := getResourceOptions(msg)
	if resOpts != nil {
		g.P("// Resource: ", resOpts.GetName())
		if resOpts.GetDescription() != "" {
			g.P("// Description: ", resOpts.GetDescription())
		}
	}

	// 分析字段
	primaryKey, uniqueIndexes, normalIndexes, compositeIndexes := analyzeFields(msg)

	// 生成资源管理器结构体
	g.P("// ", msgName, "Manager 管理", msgName, "资源的加载和访问")
	g.P("type ", msgName, "Manager struct {")
	g.P("	mu sync.RWMutex")
	g.P("	items []*", msgName)

	// 主键索引
	if primaryKey != nil {
		keyType := getGoTypeName(primaryKey.Field)
		g.P("	byPrimaryKey map[", keyType, "]*", msgName)
	}

	// 唯一索引
	for _, idx := range uniqueIndexes {
		keyType := getGoTypeName(idx.Field)
		g.P("	by", idx.Field.GoName, " map[", keyType, "]*", msgName)
	}

	// 普通索引
	for _, idx := range normalIndexes {
		keyType := getGoTypeName(idx.Field)
		g.P("	by", idx.Field.GoName, " map[", keyType, "][]*", msgName)
	}

	// 复合索引
	for name, fields := range compositeIndexes {
		keyTypeName := toCamelCase(name) + "Key"
		g.P("	by", toCamelCase(name), " map[", keyTypeName, "][]*", msgName)
		_ = fields // 后面会用到
	}

	g.P("}")
	g.P()

	// 生成复合索引的键类型
	for name, fields := range compositeIndexes {
		keyTypeName := toCamelCase(name) + "Key"
		g.P("// ", keyTypeName, " ", name, "复合索引键")
		g.P("type ", keyTypeName, " struct {")
		for _, f := range fields {
			keyType := getGoTypeName(f.Field)
			g.P("	", f.Field.GoName, " ", keyType)
		}
		g.P("}")
		g.P()
	}

	// 生成全局实例
	g.P("var (")
	g.P("	_", msgName, "Manager     *", msgName, "Manager")
	g.P("	_", msgName, "ManagerOnce sync.Once")
	g.P(")")
	g.P()

	// 生成获取管理器实例的函数
	g.P("// Get", msgName, "Manager 获取", msgName, "资源管理器单例")
	g.P("func Get", msgName, "Manager() *", msgName, "Manager {")
	g.P("	_", msgName, "ManagerOnce.Do(func() {")
	g.P("		_", msgName, "Manager = &", msgName, "Manager{}")
	g.P("	})")
	g.P("	return _", msgName, "Manager")
	g.P("}")
	g.P()

	// 生成加载函数
	g.P("// Load 从二进制文件加载资源")
	g.P("func (m *", msgName, "Manager) Load(path string) error {")
	g.P("	data, err := os.ReadFile(path)")
	g.P("	if err != nil {")
	g.P("		return fmt.Errorf(\"failed to read file: %w\", err)")
	g.P("	}")
	g.P("	return m.LoadFromBytes(data)")
	g.P("}")
	g.P()

	// 生成从字节加载函数
	g.P("// LoadFromBytes 从字节数据加载资源")
	g.P("func (m *", msgName, "Manager) LoadFromBytes(data []byte) error {")
	g.P("	if len(data) < 4 {")
	g.P("		return fmt.Errorf(\"invalid data: too short\")")
	g.P("	}")
	g.P()
	g.P("	count := binary.LittleEndian.Uint32(data[:4])")
	g.P("	offset := 4")
	g.P()
	g.P("	items := make([]*", msgName, ", 0, count)")

	// 初始化主键索引
	if primaryKey != nil {
		keyType := getGoTypeName(primaryKey.Field)
		g.P("	byPrimaryKey := make(map[", keyType, "]*", msgName, ", count)")
	}

	// 初始化唯一索引
	for _, idx := range uniqueIndexes {
		keyType := getGoTypeName(idx.Field)
		g.P("	by", idx.Field.GoName, " := make(map[", keyType, "]*", msgName, ", count)")
	}

	// 初始化普通索引
	for _, idx := range normalIndexes {
		keyType := getGoTypeName(idx.Field)
		g.P("	by", idx.Field.GoName, " := make(map[", keyType, "][]*", msgName, ")")
	}

	// 初始化复合索引
	for name := range compositeIndexes {
		keyTypeName := toCamelCase(name) + "Key"
		g.P("	by", toCamelCase(name), " := make(map[", keyTypeName, "][]*", msgName, ")")
	}

	g.P()
	g.P("	for i := uint32(0); i < count; i++ {")
	g.P("		if offset+4 > len(data) {")
	g.P("			return io.ErrUnexpectedEOF")
	g.P("		}")
	g.P("		length := binary.LittleEndian.Uint32(data[offset : offset+4])")
	g.P("		offset += 4")
	g.P()
	g.P("		if offset+int(length) > len(data) {")
	g.P("			return io.ErrUnexpectedEOF")
	g.P("		}")
	g.P()
	g.P("		item := &", msgName, "{}")
	g.P("		if err := proto.Unmarshal(data[offset:offset+int(length)], item); err != nil {")
	g.P("			return fmt.Errorf(\"failed to unmarshal item %d: %w\", i, err)")
	g.P("		}")
	g.P("		offset += int(length)")
	g.P()
	g.P("		items = append(items, item)")

	// 填充主键索引
	if primaryKey != nil {
		g.P("		byPrimaryKey[item.", primaryKey.Field.GoName, "] = item")
	}

	// 填充唯一索引
	for _, idx := range uniqueIndexes {
		g.P("		by", idx.Field.GoName, "[item.", idx.Field.GoName, "] = item")
	}

	// 填充普通索引
	for _, idx := range normalIndexes {
		g.P("		by", idx.Field.GoName, "[item.", idx.Field.GoName, "] = append(by", idx.Field.GoName, "[item.", idx.Field.GoName, "], item)")
	}

	// 填充复合索引
	for name, fields := range compositeIndexes {
		keyTypeName := toCamelCase(name) + "Key"
		g.P("		", name, "Key := ", keyTypeName, "{")
		for _, f := range fields {
			g.P("			", f.Field.GoName, ": item.", f.Field.GoName, ",")
		}
		g.P("		}")
		g.P("		by", toCamelCase(name), "[", name, "Key] = append(by", toCamelCase(name), "[", name, "Key], item)")
	}

	g.P("	}")
	g.P()
	g.P("	m.mu.Lock()")
	g.P("	m.items = items")

	if primaryKey != nil {
		g.P("	m.byPrimaryKey = byPrimaryKey")
	}
	for _, idx := range uniqueIndexes {
		g.P("	m.by", idx.Field.GoName, " = by", idx.Field.GoName)
	}
	for _, idx := range normalIndexes {
		g.P("	m.by", idx.Field.GoName, " = by", idx.Field.GoName)
	}
	for name := range compositeIndexes {
		g.P("	m.by", toCamelCase(name), " = by", toCamelCase(name))
	}

	g.P("	m.mu.Unlock()")
	g.P()
	g.P("	return nil")
	g.P("}")
	g.P()

	// 生成获取所有项目的函数
	g.P("// GetAll 获取所有", msgName, "资源")
	g.P("func (m *", msgName, "Manager) GetAll() []*", msgName, " {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	result := make([]*", msgName, ", len(m.items))")
	g.P("	copy(result, m.items)")
	g.P("	return result")
	g.P("}")
	g.P()

	// 生成获取数量的函数
	g.P("// Count 获取资源数量")
	g.P("func (m *", msgName, "Manager) Count() int {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	return len(m.items)")
	g.P("}")
	g.P()

	// 生成主键访问函数
	if primaryKey != nil {
		keyType := getGoTypeName(primaryKey.Field)
		g.P("// Get 根据主键获取", msgName)
		g.P("func (m *", msgName, "Manager) Get(key ", keyType, ") (*", msgName, ", bool) {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	item, ok := m.byPrimaryKey[key]")
		g.P("	return item, ok")
		g.P("}")
		g.P()

		g.P("// MustGet 根据主键获取", msgName, ",不存在时panic")
		g.P("func (m *", msgName, "Manager) MustGet(key ", keyType, ") *", msgName, " {")
		g.P("	item, ok := m.Get(key)")
		g.P("	if !ok {")
		g.P("		panic(fmt.Sprintf(\"", msgName, " with key %v not found\", key))")
		g.P("	}")
		g.P("	return item")
		g.P("}")
		g.P()

		g.P("// Has 检查主键是否存在")
		g.P("func (m *", msgName, "Manager) Has(key ", keyType, ") bool {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	_, ok := m.byPrimaryKey[key]")
		g.P("	return ok")
		g.P("}")
		g.P()
	}

	// 生成唯一索引访问函数
	for _, idx := range uniqueIndexes {
		keyType := getGoTypeName(idx.Field)
		g.P("// GetBy", idx.Field.GoName, " 根据", idx.Field.GoName, "获取", msgName)
		g.P("func (m *", msgName, "Manager) GetBy", idx.Field.GoName, "(key ", keyType, ") (*", msgName, ", bool) {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	item, ok := m.by", idx.Field.GoName, "[key]")
		g.P("	return item, ok")
		g.P("}")
		g.P()
	}

	// 生成普通索引访问函数
	for _, idx := range normalIndexes {
		keyType := getGoTypeName(idx.Field)
		g.P("// GetBy", idx.Field.GoName, " 根据", idx.Field.GoName, "获取", msgName, "列表")
		g.P("func (m *", msgName, "Manager) GetBy", idx.Field.GoName, "(key ", keyType, ") []*", msgName, " {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	items := m.by", idx.Field.GoName, "[key]")
		g.P("	if items == nil {")
		g.P("		return nil")
		g.P("	}")
		g.P("	result := make([]*", msgName, ", len(items))")
		g.P("	copy(result, items)")
		g.P("	return result")
		g.P("}")
		g.P()
	}

	// 生成复合索引访问函数
	for name, fields := range compositeIndexes {
		keyTypeName := toCamelCase(name) + "Key"
		funcName := "GetBy" + toCamelCase(name)

		// 生成参数列表
		params := ""
		for i, f := range fields {
			if i > 0 {
				params += ", "
			}
			params += toParamName(f.Field.GoName) + " " + getGoTypeName(f.Field)
		}

		g.P("// ", funcName, " 根据复合索引", name, "获取", msgName, "列表")
		g.P("func (m *", msgName, "Manager) ", funcName, "(", params, ") []*", msgName, " {")
		g.P("	m.mu.RLock()")
		g.P("	defer m.mu.RUnlock()")
		g.P("	key := ", keyTypeName, "{")
		for _, f := range fields {
			g.P("		", f.Field.GoName, ": ", toParamName(f.Field.GoName), ",")
		}
		g.P("	}")
		g.P("	items := m.by", toCamelCase(name), "[key]")
		g.P("	if items == nil {")
		g.P("		return nil")
		g.P("	}")
		g.P("	result := make([]*", msgName, ", len(items))")
		g.P("	copy(result, items)")
		g.P("	return result")
		g.P("}")
		g.P()
	}

	// 生成遍历函数
	g.P("// Range 遍历所有", msgName, "资源")
	g.P("func (m *", msgName, "Manager) Range(fn func(item *", msgName, ") bool) {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	for _, item := range m.items {")
	g.P("		if !fn(item) {")
	g.P("			break")
	g.P("		}")
	g.P("	}")
	g.P("}")
	g.P()

	// 生成过滤函数
	g.P("// Filter 过滤", msgName, "资源")
	g.P("func (m *", msgName, "Manager) Filter(fn func(item *", msgName, ") bool) []*", msgName, " {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	var result []*", msgName)
	g.P("	for _, item := range m.items {")
	g.P("		if fn(item) {")
	g.P("			result = append(result, item)")
	g.P("		}")
	g.P("	}")
	g.P("	return result")
	g.P("}")
	g.P()

	// 生成查找函数
	g.P("// Find 查找第一个匹配的", msgName)
	g.P("func (m *", msgName, "Manager) Find(fn func(item *", msgName, ") bool) (*", msgName, ", bool) {")
	g.P("	m.mu.RLock()")
	g.P("	defer m.mu.RUnlock()")
	g.P("	for _, item := range m.items {")
	g.P("		if fn(item) {")
	g.P("			return item, true")
	g.P("		}")
	g.P("	}")
	g.P("	return nil, false")
	g.P("}")
	g.P()
}

// getGoTypeName 获取Go类型名
func getGoTypeName(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case 1: // double
		return "float64"
	case 2: // float
		return "float32"
	case 3: // int64
		return "int64"
	case 4: // uint64
		return "uint64"
	case 5: // int32
		return "int32"
	case 6: // fixed64
		return "uint64"
	case 7: // fixed32
		return "uint32"
	case 8: // bool
		return "bool"
	case 9: // string
		return "string"
	case 12: // bytes
		return "[]byte"
	case 13: // uint32
		return "uint32"
	case 14: // enum
		return field.Enum.GoIdent.GoName
	case 15: // sfixed32
		return "int32"
	case 16: // sfixed64
		return "int64"
	case 17: // sint32
		return "int32"
	case 18: // sint64
		return "int64"
	default:
		return "interface{}"
	}
}

// toCamelCase 将下划线命名转换为驼峰命名
func toCamelCase(s string) string {
	result := ""
	upper := true
	for _, c := range s {
		if c == '_' {
			upper = true
			continue
		}
		if upper {
			if c >= 'a' && c <= 'z' {
				c = c - 'a' + 'A'
			}
			upper = false
		}
		result += string(c)
	}
	return result
}

// toParamName 将字段名转换为参数名(首字母小写)
func toParamName(s string) string {
	if len(s) == 0 {
		return s
	}
	first := s[0]
	if first >= 'A' && first <= 'Z' {
		first = first - 'A' + 'a'
	}
	return string(first) + s[1:]
}
