// resoptions.proto - 资源管理自定义选项定义
// 用于描述Excel数据的主键和索引属性

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/resoptions.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 索引类型
type IndexType int32

const (
	IndexType_INDEX_NONE      IndexType = 0 // 无索引
	IndexType_INDEX_UNIQUE    IndexType = 1 // 唯一索引
	IndexType_INDEX_NORMAL    IndexType = 2 // 普通索引(可重复)
	IndexType_INDEX_COMPOSITE IndexType = 3 // 复合索引成员
)

// Enum value maps for IndexType.
var (
	IndexType_name = map[int32]string{
		0: "INDEX_NONE",
		1: "INDEX_UNIQUE",
		2: "INDEX_NORMAL",
		3: "INDEX_COMPOSITE",
	}
	IndexType_value = map[string]int32{
		"INDEX_NONE":      0,
		"INDEX_UNIQUE":    1,
		"INDEX_NORMAL":    2,
		"INDEX_COMPOSITE": 3,
	}
)

func (x IndexType) Enum() *IndexType {
	p := new(IndexType)
	*p = x
	return p
}

func (x IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resoptions_proto_enumTypes[0].Descriptor()
}

func (IndexType) Type() protoreflect.EnumType {
	return &file_proto_resoptions_proto_enumTypes[0]
}

func (x IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexType.Descriptor instead.
func (IndexType) EnumDescriptor() ([]byte, []int) {
	return file_proto_resoptions_proto_rawDescGZIP(), []int{0}
}

type ResourceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源名称,用于生成文件名和访问接口
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Excel文件名(不含扩展名)
	ExcelFile string `protobuf:"bytes,2,opt,name=excel_file,json=excelFile,proto3" json:"excel_file,omitempty"`
	// Excel工作表名称,默认为Sheet1
	SheetName string `protobuf:"bytes,3,opt,name=sheet_name,json=sheetName,proto3" json:"sheet_name,omitempty"`
	// 是否启用热更新
	HotReload bool `protobuf:"varint,4,opt,name=hot_reload,json=hotReload,proto3" json:"hot_reload,omitempty"`
	// 资源描述
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceOptions) Reset() {
	*x = ResourceOptions{}
	mi := &file_proto_resoptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceOptions) ProtoMessage() {}

func (x *ResourceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resoptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceOptions.ProtoReflect.Descriptor instead.
func (*ResourceOptions) Descriptor() ([]byte, []int) {
	return file_proto_resoptions_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceOptions) GetExcelFile() string {
	if x != nil {
		return x.ExcelFile
	}
	return ""
}

func (x *ResourceOptions) GetSheetName() string {
	if x != nil {
		return x.SheetName
	}
	return ""
}

func (x *ResourceOptions) GetHotReload() bool {
	if x != nil {
		return x.HotReload
	}
	return false
}

func (x *ResourceOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否为主键
	PrimaryKey bool `protobuf:"varint,1,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// 索引类型
	Index IndexType `protobuf:"varint,2,opt,name=index,proto3,enum=gores.IndexType" json:"index,omitempty"`
	// 索引名称(用于复合索引分组)
	IndexName string `protobuf:"bytes,3,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	// 复合索引中的顺序
	IndexOrder int32 `protobuf:"varint,4,opt,name=index_order,json=indexOrder,proto3" json:"index_order,omitempty"`
	// Excel列名映射(如果与字段名不同)
	ColumnName string `protobuf:"bytes,5,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	// 是否必填
	Required bool `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	// 默认值(字符串形式)
	DefaultValue string `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// 字段描述
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// 嵌套消息的分隔符(用于Excel中表示嵌套结构)
	NestedSeparator string `protobuf:"bytes,9,opt,name=nested_separator,json=nestedSeparator,proto3" json:"nested_separator,omitempty"`
	// 数组分隔符(用于Excel中表示数组)
	ArraySeparator string `protobuf:"bytes,10,opt,name=array_separator,json=arraySeparator,proto3" json:"array_separator,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_proto_resoptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resoptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_proto_resoptions_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOptions) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *FieldOptions) GetIndex() IndexType {
	if x != nil {
		return x.Index
	}
	return IndexType_INDEX_NONE
}

func (x *FieldOptions) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *FieldOptions) GetIndexOrder() int32 {
	if x != nil {
		return x.IndexOrder
	}
	return 0
}

func (x *FieldOptions) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *FieldOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldOptions) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *FieldOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldOptions) GetNestedSeparator() string {
	if x != nil {
		return x.NestedSeparator
	}
	return ""
}

func (x *FieldOptions) GetArraySeparator() string {
	if x != nil {
		return x.ArraySeparator
	}
	return ""
}

type EnumValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 枚举值在Excel中的别名
	Alias string `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	// 枚举值描述
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_proto_resoptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resoptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_proto_resoptions_proto_rawDescGZIP(), []int{2}
}

func (x *EnumValueOptions) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *EnumValueOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var file_proto_resoptions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ResourceOptions)(nil),
		Field:         50001,
		Name:          "gores.resource",
		Tag:           "bytes,50001,opt,name=resource",
		Filename:      "proto/resoptions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         50002,
		Name:          "gores.field",
		Tag:           "bytes,50002,opt,name=field",
		Filename:      "proto/resoptions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         50003,
		Name:          "gores.enum_value",
		Tag:           "bytes,50003,opt,name=enum_value",
		Filename:      "proto/resoptions.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// 资源选项扩展
	//
	// optional gores.ResourceOptions resource = 50001;
	E_Resource = &file_proto_resoptions_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// 字段选项扩展
	//
	// optional gores.FieldOptions field = 50002;
	E_Field = &file_proto_resoptions_proto_extTypes[1]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional gores.EnumValueOptions enum_value = 50003;
	E_EnumValue = &file_proto_resoptions_proto_extTypes[2]
)

var File_proto_resoptions_proto protoreflect.FileDescriptor

const file_proto_resoptions_proto_rawDesc = "" +
	"\n" +
	"\x16proto/resoptions.proto\x12\x05gores\x1a google/protobuf/descriptor.proto\"\xa4\x01\n" +
	"\x0fResourceOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"excel_file\x18\x02 \x01(\tR\texcelFile\x12\x1d\n" +
	"\n" +
	"sheet_name\x18\x03 \x01(\tR\tsheetName\x12\x1d\n" +
	"\n" +
	"hot_reload\x18\x04 \x01(\bR\thotReload\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xef\x02\n" +
	"\fFieldOptions\x12\x1f\n" +
	"\vprimary_key\x18\x01 \x01(\bR\n" +
	"primaryKey\x12&\n" +
	"\x05index\x18\x02 \x01(\x0e2\x10.gores.IndexTypeR\x05index\x12\x1d\n" +
	"\n" +
	"index_name\x18\x03 \x01(\tR\tindexName\x12\x1f\n" +
	"\vindex_order\x18\x04 \x01(\x05R\n" +
	"indexOrder\x12\x1f\n" +
	"\vcolumn_name\x18\x05 \x01(\tR\n" +
	"columnName\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12)\n" +
	"\x10nested_separator\x18\t \x01(\tR\x0fnestedSeparator\x12'\n" +
	"\x0farray_separator\x18\n" +
	" \x01(\tR\x0earraySeparator\"J\n" +
	"\x10EnumValueOptions\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription*T\n" +
	"\tIndexType\x12\x0e\n" +
	"\n" +
	"INDEX_NONE\x10\x00\x12\x10\n" +
	"\fINDEX_UNIQUE\x10\x01\x12\x10\n" +
	"\fINDEX_NORMAL\x10\x02\x12\x13\n" +
	"\x0fINDEX_COMPOSITE\x10\x03:U\n" +
	"\bresource\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x16.gores.ResourceOptionsR\bresource:J\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\v2\x13.gores.FieldOptionsR\x05field:[\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18ӆ\x03 \x01(\v2\x17.gores.EnumValueOptionsR\tenumValueB Z\x1egithub.com/example/gores/protob\x06proto3"

var (
	file_proto_resoptions_proto_rawDescOnce sync.Once
	file_proto_resoptions_proto_rawDescData []byte
)

func file_proto_resoptions_proto_rawDescGZIP() []byte {
	file_proto_resoptions_proto_rawDescOnce.Do(func() {
		file_proto_resoptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resoptions_proto_rawDesc), len(file_proto_resoptions_proto_rawDesc)))
	})
	return file_proto_resoptions_proto_rawDescData
}

var file_proto_resoptions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_resoptions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_resoptions_proto_goTypes = []any{
	(IndexType)(0),                        // 0: gores.IndexType
	(*ResourceOptions)(nil),               // 1: gores.ResourceOptions
	(*FieldOptions)(nil),                  // 2: gores.FieldOptions
	(*EnumValueOptions)(nil),              // 3: gores.EnumValueOptions
	(*descriptorpb.MessageOptions)(nil),   // 4: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 5: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 6: google.protobuf.EnumValueOptions
}
var file_proto_resoptions_proto_depIdxs = []int32{
	0, // 0: gores.FieldOptions.index:type_name -> gores.IndexType
	4, // 1: gores.resource:extendee -> google.protobuf.MessageOptions
	5, // 2: gores.field:extendee -> google.protobuf.FieldOptions
	6, // 3: gores.enum_value:extendee -> google.protobuf.EnumValueOptions
	1, // 4: gores.resource:type_name -> gores.ResourceOptions
	2, // 5: gores.field:type_name -> gores.FieldOptions
	3, // 6: gores.enum_value:type_name -> gores.EnumValueOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	4, // [4:7] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_resoptions_proto_init() }
func file_proto_resoptions_proto_init() {
	if File_proto_resoptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resoptions_proto_rawDesc), len(file_proto_resoptions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_proto_resoptions_proto_goTypes,
		DependencyIndexes: file_proto_resoptions_proto_depIdxs,
		EnumInfos:         file_proto_resoptions_proto_enumTypes,
		MessageInfos:      file_proto_resoptions_proto_msgTypes,
		ExtensionInfos:    file_proto_resoptions_proto_extTypes,
	}.Build()
	File_proto_resoptions_proto = out.File
	file_proto_resoptions_proto_goTypes = nil
	file_proto_resoptions_proto_depIdxs = nil
}
