// item.proto - 物品配置表示例
// 演示如何使用自定义选项定义主键和索引

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: example/proto/item.proto

package generated

import (
	_ "github.com/example/gores/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 物品品质枚举
type ItemQuality int32

const (
	ItemQuality_QUALITY_UNKNOWN   ItemQuality = 0
	ItemQuality_QUALITY_COMMON    ItemQuality = 1 // 普通
	ItemQuality_QUALITY_UNCOMMON  ItemQuality = 2 // 精良
	ItemQuality_QUALITY_RARE      ItemQuality = 3 // 稀有
	ItemQuality_QUALITY_EPIC      ItemQuality = 4 // 史诗
	ItemQuality_QUALITY_LEGENDARY ItemQuality = 5 // 传说
)

// Enum value maps for ItemQuality.
var (
	ItemQuality_name = map[int32]string{
		0: "QUALITY_UNKNOWN",
		1: "QUALITY_COMMON",
		2: "QUALITY_UNCOMMON",
		3: "QUALITY_RARE",
		4: "QUALITY_EPIC",
		5: "QUALITY_LEGENDARY",
	}
	ItemQuality_value = map[string]int32{
		"QUALITY_UNKNOWN":   0,
		"QUALITY_COMMON":    1,
		"QUALITY_UNCOMMON":  2,
		"QUALITY_RARE":      3,
		"QUALITY_EPIC":      4,
		"QUALITY_LEGENDARY": 5,
	}
)

func (x ItemQuality) Enum() *ItemQuality {
	p := new(ItemQuality)
	*p = x
	return p
}

func (x ItemQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_item_proto_enumTypes[0].Descriptor()
}

func (ItemQuality) Type() protoreflect.EnumType {
	return &file_example_proto_item_proto_enumTypes[0]
}

func (x ItemQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemQuality.Descriptor instead.
func (ItemQuality) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_item_proto_rawDescGZIP(), []int{0}
}

// 物品类型枚举
type ItemType int32

const (
	ItemType_TYPE_UNKNOWN    ItemType = 0
	ItemType_TYPE_WEAPON     ItemType = 1 // 武器
	ItemType_TYPE_ARMOR      ItemType = 2 // 护甲
	ItemType_TYPE_CONSUMABLE ItemType = 3 // 消耗品
	ItemType_TYPE_MATERIAL   ItemType = 4 // 材料
	ItemType_TYPE_QUEST      ItemType = 5 // 任务物品
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_WEAPON",
		2: "TYPE_ARMOR",
		3: "TYPE_CONSUMABLE",
		4: "TYPE_MATERIAL",
		5: "TYPE_QUEST",
	}
	ItemType_value = map[string]int32{
		"TYPE_UNKNOWN":    0,
		"TYPE_WEAPON":     1,
		"TYPE_ARMOR":      2,
		"TYPE_CONSUMABLE": 3,
		"TYPE_MATERIAL":   4,
		"TYPE_QUEST":      5,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_item_proto_enumTypes[1].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_example_proto_item_proto_enumTypes[1]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_item_proto_rawDescGZIP(), []int{1}
}

// 物品属性(嵌套消息)
type ItemAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // 属性名
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // 属性值
	Rate          float32                `protobuf:"fixed32,3,opt,name=rate,proto3" json:"rate,omitempty"`  // 属性系数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAttribute) Reset() {
	*x = ItemAttribute{}
	mi := &file_example_proto_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAttribute) ProtoMessage() {}

func (x *ItemAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAttribute.ProtoReflect.Descriptor instead.
func (*ItemAttribute) Descriptor() ([]byte, []int) {
	return file_example_proto_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemAttribute) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ItemAttribute) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// 物品配置
type ItemConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 物品ID - 主键
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 物品名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 物品描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// 物品代码 - 唯一索引
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// 物品类型 - 普通索引
	Type ItemType `protobuf:"varint,5,opt,name=type,proto3,enum=game.ItemType" json:"type,omitempty"`
	// 物品品质 - 普通索引
	Quality ItemQuality `protobuf:"varint,6,opt,name=quality,proto3,enum=game.ItemQuality" json:"quality,omitempty"`
	// 等级要求
	LevelRequired int32 `protobuf:"varint,7,opt,name=level_required,json=levelRequired,proto3" json:"level_required,omitempty"`
	// 价格
	Price int64 `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	// 堆叠上限
	StackLimit int32 `protobuf:"varint,9,opt,name=stack_limit,json=stackLimit,proto3" json:"stack_limit,omitempty"`
	// 物品属性列表(嵌套消息数组)
	Attributes []*ItemAttribute `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// 标签
	Tags []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	// 是否可交易
	Tradeable bool `protobuf:"varint,12,opt,name=tradeable,proto3" json:"tradeable,omitempty"`
	// 图标路径
	Icon          string `protobuf:"bytes,13,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemConfig) Reset() {
	*x = ItemConfig{}
	mi := &file_example_proto_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemConfig) ProtoMessage() {}

func (x *ItemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemConfig.ProtoReflect.Descriptor instead.
func (*ItemConfig) Descriptor() ([]byte, []int) {
	return file_example_proto_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemConfig) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ItemConfig) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_TYPE_UNKNOWN
}

func (x *ItemConfig) GetQuality() ItemQuality {
	if x != nil {
		return x.Quality
	}
	return ItemQuality_QUALITY_UNKNOWN
}

func (x *ItemConfig) GetLevelRequired() int32 {
	if x != nil {
		return x.LevelRequired
	}
	return 0
}

func (x *ItemConfig) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemConfig) GetStackLimit() int32 {
	if x != nil {
		return x.StackLimit
	}
	return 0
}

func (x *ItemConfig) GetAttributes() []*ItemAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ItemConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemConfig) GetTradeable() bool {
	if x != nil {
		return x.Tradeable
	}
	return false
}

func (x *ItemConfig) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

// 技能配置
type SkillConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键
	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// 技能类型索引
	SkillType  int32   `protobuf:"varint,4,opt,name=skill_type,json=skillType,proto3" json:"skill_type,omitempty"`
	Level      int32   `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	MpCost     int32   `protobuf:"varint,6,opt,name=mp_cost,json=mpCost,proto3" json:"mp_cost,omitempty"`
	Cooldown   float32 `protobuf:"fixed32,7,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	DamageRate float32 `protobuf:"fixed32,8,opt,name=damage_rate,json=damageRate,proto3" json:"damage_rate,omitempty"`
	// 前置技能ID
	PreSkillId    int32 `protobuf:"varint,9,opt,name=pre_skill_id,json=preSkillId,proto3" json:"pre_skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillConfig) Reset() {
	*x = SkillConfig{}
	mi := &file_example_proto_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillConfig) ProtoMessage() {}

func (x *SkillConfig) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillConfig.ProtoReflect.Descriptor instead.
func (*SkillConfig) Descriptor() ([]byte, []int) {
	return file_example_proto_item_proto_rawDescGZIP(), []int{2}
}

func (x *SkillConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkillConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillConfig) GetSkillType() int32 {
	if x != nil {
		return x.SkillType
	}
	return 0
}

func (x *SkillConfig) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SkillConfig) GetMpCost() int32 {
	if x != nil {
		return x.MpCost
	}
	return 0
}

func (x *SkillConfig) GetCooldown() float32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

func (x *SkillConfig) GetDamageRate() float32 {
	if x != nil {
		return x.DamageRate
	}
	return 0
}

func (x *SkillConfig) GetPreSkillId() int32 {
	if x != nil {
		return x.PreSkillId
	}
	return 0
}

// 怪物配置(演示复合索引)
type MonsterConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键
	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 场景ID - 复合索引第一部分
	SceneId int32 `protobuf:"varint,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// 怪物类型 - 复合索引第二部分
	MonsterType int32   `protobuf:"varint,4,opt,name=monster_type,json=monsterType,proto3" json:"monster_type,omitempty"`
	Level       int32   `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Hp          int64   `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Attack      int32   `protobuf:"varint,7,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense     int32   `protobuf:"varint,8,opt,name=defense,proto3" json:"defense,omitempty"`
	AttackSpeed float32 `protobuf:"fixed32,9,opt,name=attack_speed,json=attackSpeed,proto3" json:"attack_speed,omitempty"`
	MoveSpeed   float32 `protobuf:"fixed32,10,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	// 掉落物品ID列表
	DropItems []int32 `protobuf:"varint,11,rep,packed,name=drop_items,json=dropItems,proto3" json:"drop_items,omitempty"`
	// 掉落概率(与drop_items对应)
	DropRates     []float32 `protobuf:"fixed32,12,rep,packed,name=drop_rates,json=dropRates,proto3" json:"drop_rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterConfig) Reset() {
	*x = MonsterConfig{}
	mi := &file_example_proto_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterConfig) ProtoMessage() {}

func (x *MonsterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterConfig.ProtoReflect.Descriptor instead.
func (*MonsterConfig) Descriptor() ([]byte, []int) {
	return file_example_proto_item_proto_rawDescGZIP(), []int{3}
}

func (x *MonsterConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MonsterConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MonsterConfig) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *MonsterConfig) GetMonsterType() int32 {
	if x != nil {
		return x.MonsterType
	}
	return 0
}

func (x *MonsterConfig) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MonsterConfig) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *MonsterConfig) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *MonsterConfig) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *MonsterConfig) GetAttackSpeed() float32 {
	if x != nil {
		return x.AttackSpeed
	}
	return 0
}

func (x *MonsterConfig) GetMoveSpeed() float32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *MonsterConfig) GetDropItems() []int32 {
	if x != nil {
		return x.DropItems
	}
	return nil
}

func (x *MonsterConfig) GetDropRates() []float32 {
	if x != nil {
		return x.DropRates
	}
	return nil
}

var File_example_proto_item_proto protoreflect.FileDescriptor

const file_example_proto_item_proto_rawDesc = "" +
	"\n" +
	"\x18example/proto/item.proto\x12\x04game\x1a\x16proto/resoptions.proto\"M\n" +
	"\rItemAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x02R\x04rate\"\xef\x04\n" +
	"\n" +
	"ItemConfig\x12&\n" +
	"\x02id\x18\x01 \x01(\x05B\x16\x92\xb5\x18\x12\b\x01B\x0e物品唯一IDR\x02id\x12(\n" +
	"\x04name\x18\x02 \x01(\tB\x14\x92\xb5\x18\x100\x01B\f物品名称R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\x04code\x18\x04 \x01(\tB!\x92\xb5\x18\x1d\x10\x01B\x19物品代码,全局唯一R\x04code\x128\n" +
	"\x04type\x18\x05 \x01(\x0e2\x0e.game.ItemTypeB\x14\x92\xb5\x18\x10\x10\x02B\f物品类型R\x04type\x12A\n" +
	"\aquality\x18\x06 \x01(\x0e2\x11.game.ItemQualityB\x14\x92\xb5\x18\x10\x10\x02B\f物品品质R\aquality\x12%\n" +
	"\x0elevel_required\x18\a \x01(\x05R\rlevelRequired\x12\x14\n" +
	"\x05price\x18\b \x01(\x03R\x05price\x12)\n" +
	"\vstack_limit\x18\t \x01(\x05B\b\x92\xb5\x18\x04:\x0299R\n" +
	"stackLimit\x12P\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2\x13.game.ItemAttributeB\x1b\x92\xb5\x18\x17B\x12物品属性列表R\x01|R\n" +
	"attributes\x12\x1b\n" +
	"\x04tags\x18\v \x03(\tB\a\x92\xb5\x18\x03R\x01,R\x04tags\x12\x1c\n" +
	"\ttradeable\x18\f \x01(\bR\ttradeable\x12\x12\n" +
	"\x04icon\x18\r \x01(\tR\x04icon:0\x8a\xb5\x18,\n" +
	"\x04item\x12\vitem_config\x1a\x06Sheet1*\x0f物品配置表\"\xbc\x02\n" +
	"\vSkillConfig\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x05B\x06\x92\xb5\x18\x02\b\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\n" +
	"skill_type\x18\x04 \x01(\x05B\x06\x92\xb5\x18\x02\x10\x02R\tskillType\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x17\n" +
	"\amp_cost\x18\x06 \x01(\x05R\x06mpCost\x12\x1a\n" +
	"\bcooldown\x18\a \x01(\x02R\bcooldown\x12\x1f\n" +
	"\vdamage_rate\x18\b \x01(\x02R\n" +
	"damageRate\x12 \n" +
	"\fpre_skill_id\x18\t \x01(\x05R\n" +
	"preSkillId:*\x8a\xb5\x18&\n" +
	"\x05skill\x12\fskill_config*\x0f技能配置表\"\xbf\x03\n" +
	"\rMonsterConfig\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x05B\x06\x92\xb5\x18\x02\b\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\bscene_id\x18\x03 \x01(\x05B\x14\x92\xb5\x18\x10\x10\x03\x1a\n" +
	"scene_type \x01R\asceneId\x127\n" +
	"\fmonster_type\x18\x04 \x01(\x05B\x14\x92\xb5\x18\x10\x10\x03\x1a\n" +
	"scene_type \x02R\vmonsterType\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\x03R\x02hp\x12\x16\n" +
	"\x06attack\x18\a \x01(\x05R\x06attack\x12\x18\n" +
	"\adefense\x18\b \x01(\x05R\adefense\x12!\n" +
	"\fattack_speed\x18\t \x01(\x02R\vattackSpeed\x12\x1d\n" +
	"\n" +
	"move_speed\x18\n" +
	" \x01(\x02R\tmoveSpeed\x12&\n" +
	"\n" +
	"drop_items\x18\v \x03(\x05B\a\x92\xb5\x18\x03R\x01,R\tdropItems\x12&\n" +
	"\n" +
	"drop_rates\x18\f \x03(\x02B\a\x92\xb5\x18\x03R\x01,R\tdropRates:.\x8a\xb5\x18*\n" +
	"\amonster\x12\x0emonster_config*\x0f怪物配置表*\x87\x01\n" +
	"\vItemQuality\x12\x13\n" +
	"\x0fQUALITY_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eQUALITY_COMMON\x10\x01\x12\x14\n" +
	"\x10QUALITY_UNCOMMON\x10\x02\x12\x10\n" +
	"\fQUALITY_RARE\x10\x03\x12\x10\n" +
	"\fQUALITY_EPIC\x10\x04\x12\x15\n" +
	"\x11QUALITY_LEGENDARY\x10\x05*u\n" +
	"\bItemType\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vTYPE_WEAPON\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_ARMOR\x10\x02\x12\x13\n" +
	"\x0fTYPE_CONSUMABLE\x10\x03\x12\x11\n" +
	"\rTYPE_MATERIAL\x10\x04\x12\x0e\n" +
	"\n" +
	"TYPE_QUEST\x10\x05B6Z4github.com/example/gores/example/generated;generatedb\x06proto3"

var (
	file_example_proto_item_proto_rawDescOnce sync.Once
	file_example_proto_item_proto_rawDescData []byte
)

func file_example_proto_item_proto_rawDescGZIP() []byte {
	file_example_proto_item_proto_rawDescOnce.Do(func() {
		file_example_proto_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_item_proto_rawDesc), len(file_example_proto_item_proto_rawDesc)))
	})
	return file_example_proto_item_proto_rawDescData
}

var file_example_proto_item_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_example_proto_item_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_example_proto_item_proto_goTypes = []any{
	(ItemQuality)(0),      // 0: game.ItemQuality
	(ItemType)(0),         // 1: game.ItemType
	(*ItemAttribute)(nil), // 2: game.ItemAttribute
	(*ItemConfig)(nil),    // 3: game.ItemConfig
	(*SkillConfig)(nil),   // 4: game.SkillConfig
	(*MonsterConfig)(nil), // 5: game.MonsterConfig
}
var file_example_proto_item_proto_depIdxs = []int32{
	1, // 0: game.ItemConfig.type:type_name -> game.ItemType
	0, // 1: game.ItemConfig.quality:type_name -> game.ItemQuality
	2, // 2: game.ItemConfig.attributes:type_name -> game.ItemAttribute
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_example_proto_item_proto_init() }
func file_example_proto_item_proto_init() {
	if File_example_proto_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_item_proto_rawDesc), len(file_example_proto_item_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_item_proto_goTypes,
		DependencyIndexes: file_example_proto_item_proto_depIdxs,
		EnumInfos:         file_example_proto_item_proto_enumTypes,
		MessageInfos:      file_example_proto_item_proto_msgTypes,
	}.Build()
	File_example_proto_item_proto = out.File
	file_example_proto_item_proto_goTypes = nil
	file_example_proto_item_proto_depIdxs = nil
}
