// Code generated by protoc-gen-gores. DO NOT EDIT.
// source: example/proto/item.proto

package generated

import (
	"encoding/binary"
	"fmt"
	"io"
	"os"
	"sync"

	"google.golang.org/protobuf/proto"
)

// ItemAttributeManager 管理ItemAttribute资源的加载和访问
type ItemAttributeManager struct {
	mu    sync.RWMutex
	items []*ItemAttribute
}

var (
	_ItemAttributeManager     *ItemAttributeManager
	_ItemAttributeManagerOnce sync.Once
)

// GetItemAttributeManager 获取ItemAttribute资源管理器单例
func GetItemAttributeManager() *ItemAttributeManager {
	_ItemAttributeManagerOnce.Do(func() {
		_ItemAttributeManager = &ItemAttributeManager{}
	})
	return _ItemAttributeManager
}

// Load 从二进制文件加载资源
func (m *ItemAttributeManager) Load(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}
	return m.LoadFromBytes(data)
}

// LoadFromBytes 从字节数据加载资源
func (m *ItemAttributeManager) LoadFromBytes(data []byte) error {
	if len(data) < 4 {
		return fmt.Errorf("invalid data: too short")
	}

	count := binary.LittleEndian.Uint32(data[:4])
	offset := 4

	items := make([]*ItemAttribute, 0, count)

	for i := uint32(0); i < count; i++ {
		if offset+4 > len(data) {
			return io.ErrUnexpectedEOF
		}
		length := binary.LittleEndian.Uint32(data[offset : offset+4])
		offset += 4

		if offset+int(length) > len(data) {
			return io.ErrUnexpectedEOF
		}

		item := &ItemAttribute{}
		if err := proto.Unmarshal(data[offset:offset+int(length)], item); err != nil {
			return fmt.Errorf("failed to unmarshal item %d: %w", i, err)
		}
		offset += int(length)

		items = append(items, item)
	}

	m.mu.Lock()
	m.items = items
	m.mu.Unlock()

	return nil
}

// GetAll 获取所有ItemAttribute资源
func (m *ItemAttributeManager) GetAll() []*ItemAttribute {
	m.mu.RLock()
	defer m.mu.RUnlock()
	result := make([]*ItemAttribute, len(m.items))
	copy(result, m.items)
	return result
}

// Count 获取资源数量
func (m *ItemAttributeManager) Count() int {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return len(m.items)
}

// Range 遍历所有ItemAttribute资源
func (m *ItemAttributeManager) Range(fn func(item *ItemAttribute) bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, item := range m.items {
		if !fn(item) {
			break
		}
	}
}

// Filter 过滤ItemAttribute资源
func (m *ItemAttributeManager) Filter(fn func(item *ItemAttribute) bool) []*ItemAttribute {
	m.mu.RLock()
	defer m.mu.RUnlock()
	var result []*ItemAttribute
	for _, item := range m.items {
		if fn(item) {
			result = append(result, item)
		}
	}
	return result
}

// Find 查找第一个匹配的ItemAttribute
func (m *ItemAttributeManager) Find(fn func(item *ItemAttribute) bool) (*ItemAttribute, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, item := range m.items {
		if fn(item) {
			return item, true
		}
	}
	return nil, false
}

// Resource: item
// Description: 物品配置表
// ItemConfigManager 管理ItemConfig资源的加载和访问
type ItemConfigManager struct {
	mu           sync.RWMutex
	items        []*ItemConfig
	byPrimaryKey map[int32]*ItemConfig
	byCode       map[string]*ItemConfig
	byType       map[ItemType][]*ItemConfig
	byQuality    map[ItemQuality][]*ItemConfig
}

var (
	_ItemConfigManager     *ItemConfigManager
	_ItemConfigManagerOnce sync.Once
)

// GetItemConfigManager 获取ItemConfig资源管理器单例
func GetItemConfigManager() *ItemConfigManager {
	_ItemConfigManagerOnce.Do(func() {
		_ItemConfigManager = &ItemConfigManager{}
	})
	return _ItemConfigManager
}

// Load 从二进制文件加载资源
func (m *ItemConfigManager) Load(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}
	return m.LoadFromBytes(data)
}

// LoadFromBytes 从字节数据加载资源
func (m *ItemConfigManager) LoadFromBytes(data []byte) error {
	if len(data) < 4 {
		return fmt.Errorf("invalid data: too short")
	}

	count := binary.LittleEndian.Uint32(data[:4])
	offset := 4

	items := make([]*ItemConfig, 0, count)
	byPrimaryKey := make(map[int32]*ItemConfig, count)
	byCode := make(map[string]*ItemConfig, count)
	byType := make(map[ItemType][]*ItemConfig)
	byQuality := make(map[ItemQuality][]*ItemConfig)

	for i := uint32(0); i < count; i++ {
		if offset+4 > len(data) {
			return io.ErrUnexpectedEOF
		}
		length := binary.LittleEndian.Uint32(data[offset : offset+4])
		offset += 4

		if offset+int(length) > len(data) {
			return io.ErrUnexpectedEOF
		}

		item := &ItemConfig{}
		if err := proto.Unmarshal(data[offset:offset+int(length)], item); err != nil {
			return fmt.Errorf("failed to unmarshal item %d: %w", i, err)
		}
		offset += int(length)

		items = append(items, item)
		byPrimaryKey[item.Id] = item
		byCode[item.Code] = item
		byType[item.Type] = append(byType[item.Type], item)
		byQuality[item.Quality] = append(byQuality[item.Quality], item)
	}

	m.mu.Lock()
	m.items = items
	m.byPrimaryKey = byPrimaryKey
	m.byCode = byCode
	m.byType = byType
	m.byQuality = byQuality
	m.mu.Unlock()

	return nil
}

// GetAll 获取所有ItemConfig资源
func (m *ItemConfigManager) GetAll() []*ItemConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	result := make([]*ItemConfig, len(m.items))
	copy(result, m.items)
	return result
}

// Count 获取资源数量
func (m *ItemConfigManager) Count() int {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return len(m.items)
}

// Get 根据主键获取ItemConfig
func (m *ItemConfigManager) Get(key int32) (*ItemConfig, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	item, ok := m.byPrimaryKey[key]
	return item, ok
}

// MustGet 根据主键获取ItemConfig,不存在时panic
func (m *ItemConfigManager) MustGet(key int32) *ItemConfig {
	item, ok := m.Get(key)
	if !ok {
		panic(fmt.Sprintf("ItemConfig with key %v not found", key))
	}
	return item
}

// Has 检查主键是否存在
func (m *ItemConfigManager) Has(key int32) bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	_, ok := m.byPrimaryKey[key]
	return ok
}

// GetByCode 根据Code获取ItemConfig
func (m *ItemConfigManager) GetByCode(key string) (*ItemConfig, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	item, ok := m.byCode[key]
	return item, ok
}

// GetByType 根据Type获取ItemConfig列表
func (m *ItemConfigManager) GetByType(key ItemType) []*ItemConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	items := m.byType[key]
	if items == nil {
		return nil
	}
	result := make([]*ItemConfig, len(items))
	copy(result, items)
	return result
}

// GetByQuality 根据Quality获取ItemConfig列表
func (m *ItemConfigManager) GetByQuality(key ItemQuality) []*ItemConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	items := m.byQuality[key]
	if items == nil {
		return nil
	}
	result := make([]*ItemConfig, len(items))
	copy(result, items)
	return result
}

// Range 遍历所有ItemConfig资源
func (m *ItemConfigManager) Range(fn func(item *ItemConfig) bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, item := range m.items {
		if !fn(item) {
			break
		}
	}
}

// Filter 过滤ItemConfig资源
func (m *ItemConfigManager) Filter(fn func(item *ItemConfig) bool) []*ItemConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	var result []*ItemConfig
	for _, item := range m.items {
		if fn(item) {
			result = append(result, item)
		}
	}
	return result
}

// Find 查找第一个匹配的ItemConfig
func (m *ItemConfigManager) Find(fn func(item *ItemConfig) bool) (*ItemConfig, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, item := range m.items {
		if fn(item) {
			return item, true
		}
	}
	return nil, false
}

// Resource: skill
// Description: 技能配置表
// SkillConfigManager 管理SkillConfig资源的加载和访问
type SkillConfigManager struct {
	mu           sync.RWMutex
	items        []*SkillConfig
	byPrimaryKey map[int32]*SkillConfig
	bySkillType  map[int32][]*SkillConfig
}

var (
	_SkillConfigManager     *SkillConfigManager
	_SkillConfigManagerOnce sync.Once
)

// GetSkillConfigManager 获取SkillConfig资源管理器单例
func GetSkillConfigManager() *SkillConfigManager {
	_SkillConfigManagerOnce.Do(func() {
		_SkillConfigManager = &SkillConfigManager{}
	})
	return _SkillConfigManager
}

// Load 从二进制文件加载资源
func (m *SkillConfigManager) Load(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}
	return m.LoadFromBytes(data)
}

// LoadFromBytes 从字节数据加载资源
func (m *SkillConfigManager) LoadFromBytes(data []byte) error {
	if len(data) < 4 {
		return fmt.Errorf("invalid data: too short")
	}

	count := binary.LittleEndian.Uint32(data[:4])
	offset := 4

	items := make([]*SkillConfig, 0, count)
	byPrimaryKey := make(map[int32]*SkillConfig, count)
	bySkillType := make(map[int32][]*SkillConfig)

	for i := uint32(0); i < count; i++ {
		if offset+4 > len(data) {
			return io.ErrUnexpectedEOF
		}
		length := binary.LittleEndian.Uint32(data[offset : offset+4])
		offset += 4

		if offset+int(length) > len(data) {
			return io.ErrUnexpectedEOF
		}

		item := &SkillConfig{}
		if err := proto.Unmarshal(data[offset:offset+int(length)], item); err != nil {
			return fmt.Errorf("failed to unmarshal item %d: %w", i, err)
		}
		offset += int(length)

		items = append(items, item)
		byPrimaryKey[item.Id] = item
		bySkillType[item.SkillType] = append(bySkillType[item.SkillType], item)
	}

	m.mu.Lock()
	m.items = items
	m.byPrimaryKey = byPrimaryKey
	m.bySkillType = bySkillType
	m.mu.Unlock()

	return nil
}

// GetAll 获取所有SkillConfig资源
func (m *SkillConfigManager) GetAll() []*SkillConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	result := make([]*SkillConfig, len(m.items))
	copy(result, m.items)
	return result
}

// Count 获取资源数量
func (m *SkillConfigManager) Count() int {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return len(m.items)
}

// Get 根据主键获取SkillConfig
func (m *SkillConfigManager) Get(key int32) (*SkillConfig, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	item, ok := m.byPrimaryKey[key]
	return item, ok
}

// MustGet 根据主键获取SkillConfig,不存在时panic
func (m *SkillConfigManager) MustGet(key int32) *SkillConfig {
	item, ok := m.Get(key)
	if !ok {
		panic(fmt.Sprintf("SkillConfig with key %v not found", key))
	}
	return item
}

// Has 检查主键是否存在
func (m *SkillConfigManager) Has(key int32) bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	_, ok := m.byPrimaryKey[key]
	return ok
}

// GetBySkillType 根据SkillType获取SkillConfig列表
func (m *SkillConfigManager) GetBySkillType(key int32) []*SkillConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	items := m.bySkillType[key]
	if items == nil {
		return nil
	}
	result := make([]*SkillConfig, len(items))
	copy(result, items)
	return result
}

// Range 遍历所有SkillConfig资源
func (m *SkillConfigManager) Range(fn func(item *SkillConfig) bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, item := range m.items {
		if !fn(item) {
			break
		}
	}
}

// Filter 过滤SkillConfig资源
func (m *SkillConfigManager) Filter(fn func(item *SkillConfig) bool) []*SkillConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	var result []*SkillConfig
	for _, item := range m.items {
		if fn(item) {
			result = append(result, item)
		}
	}
	return result
}

// Find 查找第一个匹配的SkillConfig
func (m *SkillConfigManager) Find(fn func(item *SkillConfig) bool) (*SkillConfig, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, item := range m.items {
		if fn(item) {
			return item, true
		}
	}
	return nil, false
}

// Resource: monster
// Description: 怪物配置表
// MonsterConfigManager 管理MonsterConfig资源的加载和访问
type MonsterConfigManager struct {
	mu           sync.RWMutex
	items        []*MonsterConfig
	byPrimaryKey map[int32]*MonsterConfig
	bySceneType  map[SceneTypeKey][]*MonsterConfig
}

// SceneTypeKey scene_type复合索引键
type SceneTypeKey struct {
	SceneId     int32
	MonsterType int32
}

var (
	_MonsterConfigManager     *MonsterConfigManager
	_MonsterConfigManagerOnce sync.Once
)

// GetMonsterConfigManager 获取MonsterConfig资源管理器单例
func GetMonsterConfigManager() *MonsterConfigManager {
	_MonsterConfigManagerOnce.Do(func() {
		_MonsterConfigManager = &MonsterConfigManager{}
	})
	return _MonsterConfigManager
}

// Load 从二进制文件加载资源
func (m *MonsterConfigManager) Load(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}
	return m.LoadFromBytes(data)
}

// LoadFromBytes 从字节数据加载资源
func (m *MonsterConfigManager) LoadFromBytes(data []byte) error {
	if len(data) < 4 {
		return fmt.Errorf("invalid data: too short")
	}

	count := binary.LittleEndian.Uint32(data[:4])
	offset := 4

	items := make([]*MonsterConfig, 0, count)
	byPrimaryKey := make(map[int32]*MonsterConfig, count)
	bySceneType := make(map[SceneTypeKey][]*MonsterConfig)

	for i := uint32(0); i < count; i++ {
		if offset+4 > len(data) {
			return io.ErrUnexpectedEOF
		}
		length := binary.LittleEndian.Uint32(data[offset : offset+4])
		offset += 4

		if offset+int(length) > len(data) {
			return io.ErrUnexpectedEOF
		}

		item := &MonsterConfig{}
		if err := proto.Unmarshal(data[offset:offset+int(length)], item); err != nil {
			return fmt.Errorf("failed to unmarshal item %d: %w", i, err)
		}
		offset += int(length)

		items = append(items, item)
		byPrimaryKey[item.Id] = item
		scene_typeKey := SceneTypeKey{
			SceneId:     item.SceneId,
			MonsterType: item.MonsterType,
		}
		bySceneType[scene_typeKey] = append(bySceneType[scene_typeKey], item)
	}

	m.mu.Lock()
	m.items = items
	m.byPrimaryKey = byPrimaryKey
	m.bySceneType = bySceneType
	m.mu.Unlock()

	return nil
}

// GetAll 获取所有MonsterConfig资源
func (m *MonsterConfigManager) GetAll() []*MonsterConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	result := make([]*MonsterConfig, len(m.items))
	copy(result, m.items)
	return result
}

// Count 获取资源数量
func (m *MonsterConfigManager) Count() int {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return len(m.items)
}

// Get 根据主键获取MonsterConfig
func (m *MonsterConfigManager) Get(key int32) (*MonsterConfig, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	item, ok := m.byPrimaryKey[key]
	return item, ok
}

// MustGet 根据主键获取MonsterConfig,不存在时panic
func (m *MonsterConfigManager) MustGet(key int32) *MonsterConfig {
	item, ok := m.Get(key)
	if !ok {
		panic(fmt.Sprintf("MonsterConfig with key %v not found", key))
	}
	return item
}

// Has 检查主键是否存在
func (m *MonsterConfigManager) Has(key int32) bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	_, ok := m.byPrimaryKey[key]
	return ok
}

// GetBySceneType 根据复合索引scene_type获取MonsterConfig列表
func (m *MonsterConfigManager) GetBySceneType(sceneId int32, monsterType int32) []*MonsterConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	key := SceneTypeKey{
		SceneId:     sceneId,
		MonsterType: monsterType,
	}
	items := m.bySceneType[key]
	if items == nil {
		return nil
	}
	result := make([]*MonsterConfig, len(items))
	copy(result, items)
	return result
}

// Range 遍历所有MonsterConfig资源
func (m *MonsterConfigManager) Range(fn func(item *MonsterConfig) bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, item := range m.items {
		if !fn(item) {
			break
		}
	}
}

// Filter 过滤MonsterConfig资源
func (m *MonsterConfigManager) Filter(fn func(item *MonsterConfig) bool) []*MonsterConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	var result []*MonsterConfig
	for _, item := range m.items {
		if fn(item) {
			result = append(result, item)
		}
	}
	return result
}

// Find 查找第一个匹配的MonsterConfig
func (m *MonsterConfigManager) Find(fn func(item *MonsterConfig) bool) (*MonsterConfig, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, item := range m.items {
		if fn(item) {
			return item, true
		}
	}
	return nil, false
}
